---
aws_region: "eu-central-1"
aws_instance_type: "t3.micro"
aws_key_pair: "MyKeyPair"
aws_security_group_ids:
  - sg-007c4d152a6a96ad6  # default VPC security group
  - sg-04692a26ae0bff936  # ssh-security-group
aws_tag_snapshot: "true"
aws_tag_environment: "Test"
aws_tag_role: "DevOps"
aws_volume_size: 10
aws_vpc_id: "vpc-0a9de6337ea6dd6c3"
aws_subnet_id: subnet-06d6d45fb7dd30a40
aws_assign_public_ip: true
aws_assign_elastic_ip: "absent"
