---
- name: Run security_group tasks
  ansible.builtin.import_tasks:
    file: security_group.yml

- name: Run ec2 tasks
  ansible.builtin.import_tasks:
    file: ec2.yml

- name: Run elastic_ip tasks
  ansible.builtin.import_tasks:
    file: elastic_ip.yml
